/* eslint-disable no-restricted-globals */
/* eslint-disable no-underscore-dangle */

import { clientsClaim } from "workbox-core";
import { ExpirationPlugin } from "workbox-expiration";
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { NetworkFirst, StaleWhileRevalidate } from "workbox-strategies";

// Activate new service worker as soon as it finishes installing.
self.skipWaiting();
clientsClaim();

// Precache all of the assets generated by the build process.
precacheAndRoute(self.__WB_MANIFEST);

// Provide an SPA-friendly offline fallback for navigation requests.
const fileExtensionRegexp = new RegExp("/[^/?]+\\.[^/]+$");
registerRoute(
  ({ request, url }) =>
    request.mode === "navigate" &&
    !url.pathname.startsWith("/_") &&
    !url.pathname.match(fileExtensionRegexp),
  createHandlerBoundToURL(`${process.env.PUBLIC_URL}/index.html`)
);

// Runtime caching: API reads use stale-while-revalidate for fast responses.
registerRoute(
  ({ url, request }) =>
    request.method === "GET" && url.origin === self.location.origin && url.pathname.startsWith("/api/"),
  new StaleWhileRevalidate({
    cacheName: "api-read-cache",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60,
        purgeOnQuotaError: true,
      }),
    ],
  })
);

// Runtime caching: user-specific or mutating requests favor the network first.
registerRoute(
  ({ url, request }) =>
    request.method !== "GET" &&
    url.origin === self.location.origin &&
    url.pathname.startsWith("/api/"),
  new NetworkFirst({
    cacheName: "api-user-cache",
    networkTimeoutSeconds: 5,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 10 * 60,
        purgeOnQuotaError: true,
      }),
    ],
  })
);
